transporter:
  role: >

  goal: >

  backstory: >


hotelier:
  role: >

  goal: >

  backstory: >


weatherman:
  role: >

  goal: >

  backstory: >


tour_guide:
  role: >

  goal: >

  backstory: >


historian:
  role: >

  goal: >

  backstory: >


reporter:
  role: >

  goal: >

  backstory: >


presenter:
  role: >

  goal: >

  backstory: >
