find_transportation:
  description: >
    The goal is finding all the possible transportation services in {destination} in between {start_date} and {end_date}.
    And looking into the best options from each category (train, flight and car rental) in terms of price and duration.
    The user wants to know the price of each transportation service, the duration of each transportation service as well as the 
    type of transportation services available. The user cares a lot about the cheap price but wants to balance that with the
    duration of the journey as well.
  expected_output: >
    The output should a bullet point list of the best options from each category (train, flight and car rental) in terms 
    of price and duration of the trip.
  agent: train_finder, flight_finder, car_rental_finder


find_hotel:
  description: >
    The user wants to know all the possible hotel and AirBnB options in {destination} in between {start_date} and {end_date}. 
    The user wants to know the price of each hotel and AirBnB, the duration of each hotel and AirBnB stay as well as the 
    type of hotel and AirBnB available for stay and their qualities. Lastly, out of all the hotel and AirBnB options, 
    the user wants to know the best options from each category (hotel and AirBnB) in terms of price, quality and amenities.    
  expected_output: >
    The output should a bullet point list of the best 2 options from each category (hotel and AirBnB) in terms of 
    price, quality and amenities.
  agent: hotel_finder, airbnb_finder


get_weather:
  description: >
    The user wants to know the weather forecast of {destination} in between {start_date} and {end_date} so that they can
    prepare for the trip accordingly. The user wants to know the temperature, humidity and precipitation forecast for each day.
    And they want to know should they bring/wear for their trip (clothing, umberella etc). 
  expected_output: >
    The output should be a list of the weather forecast for each day in between {start_date} and {end_date} and the 
    list of items that the user should bring/wear for the trip for each day.
  agent: weatherman, clothing_advisor


get_activities:
  description: >
    The user wants to know the best activities and places to visit in {destination} in between {start_date} and {end_date}.
    The user wants to know the top 5 activities, top 5 museums and top 5 restaurants/bars/coffe shops
    in {destination} in between {start_date} and {end_date}.
  expected_output: >
    The output should be a bullet point list of the top 5 activities, top 5 museums and top 5 restaurants/bars/coffe shops
    in {destination} in between {start_date} and {end_date}.
  agent: museum_finder, restaurant_finder, activity_finder


get_history:
  description: >
    The user wants to know the history of {destination} so that they can learn more about the place they are visiting.
    The user wants to know the history of {destination} in terms of the historical events, historical places and historical
    figures of {destination} as well as fun facts.
  expected_output: >
    The output should be a paragraph of 4 sentences of the historical events, historical places and historical figures of 
    {destination} as well as fun facts.
  agent: historian


get_presentation:
  description: >
    The user wants to get a power point presentation of their trip to {destination} in between {start_date} and {end_date} that includes
    the best transportation options, the best hotel and AirBnB options, the weather forecast, the best activities and places to visit
    and the history of {destination}.
  expected_output: >
    This presentation will include the transportation options, hotel options, weather forecast, clothing advice, activities,
    museums, restaurants/bars/coffe shops and should be 10 Slides long with a fun introduction and conclusion Slide.
    The presentation should be visually appealing and should be easy to understand. Find visually appealing images for each slide.  
  agent: train_finder, flight_finder, car_rental_finder, hotel_finder, airbnb_finder, weatherman, clothing_advisor, museum_finder, 
  restaurant_finder, activity_finder, historian