find_transportation:
  description: >
    
  expected_output: >
    
  agent: train_finder, flight_finder, car_rental_finder, transporter

find_hotel:
  description: >
    
  expected_output: >
    
  agent: hotelier


get_weather:
  description: >
    
  expected_output: >
    
  agent: weatherman


get_activities:
  description: >
    
  expected_output: >
    
  agent: tour_guide


get_history:
  description: >
    
  expected_output: >
    
  agent: historian

get_report:
  description: >
    
  expected_output: >
    
  agent: reporter


get_presentation:
  description: >
    
  expected_output: >
    
  agent: presenter

